

spring:
  application:
    name: biblioteca
  datasource:
    url: jdbc:postgresql://localhost:5432/biblioteca
    username: postgres
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect